[package]
name = "rust_core"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.172"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full"] }
